version: '3'

services:

  agent25:
    build: .
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=ballad-recons.0z@icloud.com

  agent26:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=polish.tales05@icloud.com

  agent27:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=01legion.pep@icloud.com

  agent28:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=tole-tiers-0q@icloud.com

  agent29:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=warm-musher0d@icloud.com

  agent30:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=maze-09tropes@icloud.com

  agent31:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=waffles-passive.0c@icloud.com

  agent32:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=prover.fluffy_0q@icloud.com

  agent33:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=pubs-corral0r@icloud.com

  agent34:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=azure.thrifts_0j@icloud.com

  agent35:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=sob.tokay-0a@icloud.com
