version: '3'

services:

  agent1:
    build: .
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=scoots-grassy-0h@icloud.com
      - LOOTBOXES_ALLOWED=True

  agent2:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=corner-biliary0l@icloud.com
      - LOOTBOXES_ALLOWED=True

  agent3:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=boxy.crumbs-0e@icloud.com

  agent4:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=joule.05-sobs@icloud.com

  agent5:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=flouncy_regent0l@icloud.com

  agent6:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=hotbed.paddle.0a@icloud.com

  agent7:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=beers.dares.0n@icloud.com

  agent8:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=concord06_booker@icloud.com

  agent9:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=congers_coldest0u@icloud.com

  agent10:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=grub-healing-0x@icloud.com

  agent11:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=boss-02-pendant@icloud.com

  agent12:
    image: stepapp-bot
    command: ['python', 'app/agent.py']
    restart: always
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      - EMAIL=gutsy.grantor04@icloud.com
