version: '3'

services:

  watcher:
    build: .
    image: stepapp-bot
    command: ['python', 'app/watcher.py']
    restart: always
    depends_on:
      - redis
    volumes:
      - .:/opt/app
    environment:
      - DEBUG=true
      - ENVIRONMENT=development
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@redis:6379/0
      - EMAIL=piste.cloths-0j@icloud.com
      - PASSWORD=${PASSWORD}
      - MAX_PRICE=${MAX_PRICE}

  redis:
    image: redis
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - 63179:6379
    expose:
      - "6379"
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
