version: '3'

services:

  watcher:
    build: .
    image: stepapp-bot
    command: ['python', 'app/watcher.py']
    restart: always
    depends_on:
      - redis
    volumes:
      - .:/opt/app
    env_file:
      - .env

  redis:
    image: redis
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - 63179:6379
    expose:
      - "6379"
    env_file:
      - .env
